### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Oxicode**

### CODE REVIEW

**Comment by richardforth** [comment]
Curl doesn't need the http://. This merge request isn't necessary.

**Comment by Oxicode** [comment]
En Ubuntu no funciona sin el http

**Comment by richardforth** [comment]
image

Can you please paste what you see, as I don't have that issue, and never have, in over 4 years of development.

**Comment by richardforth** [comment]
¿Puede por favor pegar lo que ve, ya que no tengo ese problema, y nunca lo he hecho, en más de 4 años de desarrollo.

(Google Translate)

Can you please paste what you see, as I don't have that issue, and never have, in over 4 years of development.

**Comment by Oxicode** [comment]
Sorry, my error

**Pull request closed without merging**
