### PR TITLE
fix issues around maxrequestworkers value

### PR DESCRIPTION
**Pull request by jboulen**
- fix default maxRequestWorkers value calculation
- enable ThreadsPerChild calculation for mpm_event
- fix some apache documentation links

### CODE REVIEW

**Comment by jboulen** [comment]
According to [Apache 2.4 documentation](https://httpd.apache.org/docs/2.4/en/mod/mpm_common.html#maxrequestworkers), for mpm event, default MaxRequestWorkers value is the result of $serverlimit * $threadsperchild.
Currently, apache2buddy uses the static value [16](https://github.com/richardforth/apache2buddy/blob/master/apache2buddy.pl#L1638).

**Comment by richardforth** [comment]
Awesome work, I'm planning on doing some additional work on it next week, it looks safe to merge but I am a doofus at git/gihub so bear with me, I'm still learning.

**Comment by richardforth** [comment]
I'm assuming the issue I am having is that this pull was made from the master branch, but I have a staging branch where I test the changes before merging into master (master is live, aka where the domain points at, so if we break master, the script doesn't work).

I really want to merge it with staging, but I don't have that option, I think that's what I'm struggling with.

If I gracefully reject this pull request would you be able to make the same change in a pull request from staging instead? I'll then be able to test and merge in to master later.

I'll leave this open for now.

Cheers
Richard

**Comment by jboulen** [comment]
Thank you. I changed to staging branch. I hope it will be ok.

**Comment by richardforth** [comment]
Hi,

I've successfully merged into staging, pending some testing next week, I'll hope to push this live.

Thanks for your contribution :)

**Pull request merged**
